/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package facebook.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FacebookPost extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 400294170948456412L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FacebookPost\",\"namespace\":\"facebook.avro\",\"fields\":[{\"name\":\"status_id\",\"type\":\"string\"},{\"name\":\"status_message\",\"type\":\"string\"},{\"name\":\"link_name\",\"type\":\"string\"},{\"name\":\"status_type\",\"type\":\"string\"},{\"name\":\"status_link\",\"type\":\"string\"},{\"name\":\"status_published\",\"type\":\"string\"},{\"name\":\"num_reactions\",\"type\":\"int\"},{\"name\":\"num_comments\",\"type\":\"int\"},{\"name\":\"num_shares\",\"type\":\"int\"},{\"name\":\"num_likes\",\"type\":\"int\"},{\"name\":\"num_loves\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence status_id;
  @Deprecated public java.lang.CharSequence status_message;
  @Deprecated public java.lang.CharSequence link_name;
  @Deprecated public java.lang.CharSequence status_type;
  @Deprecated public java.lang.CharSequence status_link;
  @Deprecated public java.lang.CharSequence status_published;
  @Deprecated public int num_reactions;
  @Deprecated public int num_comments;
  @Deprecated public int num_shares;
  @Deprecated public int num_likes;
  @Deprecated public int num_loves;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FacebookPost() {}

  /**
   * All-args constructor.
   * @param status_id The new value for status_id
   * @param status_message The new value for status_message
   * @param link_name The new value for link_name
   * @param status_type The new value for status_type
   * @param status_link The new value for status_link
   * @param status_published The new value for status_published
   * @param num_reactions The new value for num_reactions
   * @param num_comments The new value for num_comments
   * @param num_shares The new value for num_shares
   * @param num_likes The new value for num_likes
   * @param num_loves The new value for num_loves
   */
  public FacebookPost(java.lang.CharSequence status_id, java.lang.CharSequence status_message, java.lang.CharSequence link_name, java.lang.CharSequence status_type, java.lang.CharSequence status_link, java.lang.CharSequence status_published, java.lang.Integer num_reactions, java.lang.Integer num_comments, java.lang.Integer num_shares, java.lang.Integer num_likes, java.lang.Integer num_loves) {
    this.status_id = status_id;
    this.status_message = status_message;
    this.link_name = link_name;
    this.status_type = status_type;
    this.status_link = status_link;
    this.status_published = status_published;
    this.num_reactions = num_reactions;
    this.num_comments = num_comments;
    this.num_shares = num_shares;
    this.num_likes = num_likes;
    this.num_loves = num_loves;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status_id;
    case 1: return status_message;
    case 2: return link_name;
    case 3: return status_type;
    case 4: return status_link;
    case 5: return status_published;
    case 6: return num_reactions;
    case 7: return num_comments;
    case 8: return num_shares;
    case 9: return num_likes;
    case 10: return num_loves;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status_id = (java.lang.CharSequence)value$; break;
    case 1: status_message = (java.lang.CharSequence)value$; break;
    case 2: link_name = (java.lang.CharSequence)value$; break;
    case 3: status_type = (java.lang.CharSequence)value$; break;
    case 4: status_link = (java.lang.CharSequence)value$; break;
    case 5: status_published = (java.lang.CharSequence)value$; break;
    case 6: num_reactions = (java.lang.Integer)value$; break;
    case 7: num_comments = (java.lang.Integer)value$; break;
    case 8: num_shares = (java.lang.Integer)value$; break;
    case 9: num_likes = (java.lang.Integer)value$; break;
    case 10: num_loves = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'status_id' field.
   * @return The value of the 'status_id' field.
   */
  public java.lang.CharSequence getStatusId() {
    return status_id;
  }

  /**
   * Sets the value of the 'status_id' field.
   * @param value the value to set.
   */
  public void setStatusId(java.lang.CharSequence value) {
    this.status_id = value;
  }

  /**
   * Gets the value of the 'status_message' field.
   * @return The value of the 'status_message' field.
   */
  public java.lang.CharSequence getStatusMessage() {
    return status_message;
  }

  /**
   * Sets the value of the 'status_message' field.
   * @param value the value to set.
   */
  public void setStatusMessage(java.lang.CharSequence value) {
    this.status_message = value;
  }

  /**
   * Gets the value of the 'link_name' field.
   * @return The value of the 'link_name' field.
   */
  public java.lang.CharSequence getLinkName() {
    return link_name;
  }

  /**
   * Sets the value of the 'link_name' field.
   * @param value the value to set.
   */
  public void setLinkName(java.lang.CharSequence value) {
    this.link_name = value;
  }

  /**
   * Gets the value of the 'status_type' field.
   * @return The value of the 'status_type' field.
   */
  public java.lang.CharSequence getStatusType() {
    return status_type;
  }

  /**
   * Sets the value of the 'status_type' field.
   * @param value the value to set.
   */
  public void setStatusType(java.lang.CharSequence value) {
    this.status_type = value;
  }

  /**
   * Gets the value of the 'status_link' field.
   * @return The value of the 'status_link' field.
   */
  public java.lang.CharSequence getStatusLink() {
    return status_link;
  }

  /**
   * Sets the value of the 'status_link' field.
   * @param value the value to set.
   */
  public void setStatusLink(java.lang.CharSequence value) {
    this.status_link = value;
  }

  /**
   * Gets the value of the 'status_published' field.
   * @return The value of the 'status_published' field.
   */
  public java.lang.CharSequence getStatusPublished() {
    return status_published;
  }

  /**
   * Sets the value of the 'status_published' field.
   * @param value the value to set.
   */
  public void setStatusPublished(java.lang.CharSequence value) {
    this.status_published = value;
  }

  /**
   * Gets the value of the 'num_reactions' field.
   * @return The value of the 'num_reactions' field.
   */
  public java.lang.Integer getNumReactions() {
    return num_reactions;
  }

  /**
   * Sets the value of the 'num_reactions' field.
   * @param value the value to set.
   */
  public void setNumReactions(java.lang.Integer value) {
    this.num_reactions = value;
  }

  /**
   * Gets the value of the 'num_comments' field.
   * @return The value of the 'num_comments' field.
   */
  public java.lang.Integer getNumComments() {
    return num_comments;
  }

  /**
   * Sets the value of the 'num_comments' field.
   * @param value the value to set.
   */
  public void setNumComments(java.lang.Integer value) {
    this.num_comments = value;
  }

  /**
   * Gets the value of the 'num_shares' field.
   * @return The value of the 'num_shares' field.
   */
  public java.lang.Integer getNumShares() {
    return num_shares;
  }

  /**
   * Sets the value of the 'num_shares' field.
   * @param value the value to set.
   */
  public void setNumShares(java.lang.Integer value) {
    this.num_shares = value;
  }

  /**
   * Gets the value of the 'num_likes' field.
   * @return The value of the 'num_likes' field.
   */
  public java.lang.Integer getNumLikes() {
    return num_likes;
  }

  /**
   * Sets the value of the 'num_likes' field.
   * @param value the value to set.
   */
  public void setNumLikes(java.lang.Integer value) {
    this.num_likes = value;
  }

  /**
   * Gets the value of the 'num_loves' field.
   * @return The value of the 'num_loves' field.
   */
  public java.lang.Integer getNumLoves() {
    return num_loves;
  }

  /**
   * Sets the value of the 'num_loves' field.
   * @param value the value to set.
   */
  public void setNumLoves(java.lang.Integer value) {
    this.num_loves = value;
  }

  /**
   * Creates a new FacebookPost RecordBuilder.
   * @return A new FacebookPost RecordBuilder
   */
  public static facebook.avro.FacebookPost.Builder newBuilder() {
    return new facebook.avro.FacebookPost.Builder();
  }

  /**
   * Creates a new FacebookPost RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FacebookPost RecordBuilder
   */
  public static facebook.avro.FacebookPost.Builder newBuilder(facebook.avro.FacebookPost.Builder other) {
    return new facebook.avro.FacebookPost.Builder(other);
  }

  /**
   * Creates a new FacebookPost RecordBuilder by copying an existing FacebookPost instance.
   * @param other The existing instance to copy.
   * @return A new FacebookPost RecordBuilder
   */
  public static facebook.avro.FacebookPost.Builder newBuilder(facebook.avro.FacebookPost other) {
    return new facebook.avro.FacebookPost.Builder(other);
  }

  /**
   * RecordBuilder for FacebookPost instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FacebookPost>
    implements org.apache.avro.data.RecordBuilder<FacebookPost> {

    private java.lang.CharSequence status_id;
    private java.lang.CharSequence status_message;
    private java.lang.CharSequence link_name;
    private java.lang.CharSequence status_type;
    private java.lang.CharSequence status_link;
    private java.lang.CharSequence status_published;
    private int num_reactions;
    private int num_comments;
    private int num_shares;
    private int num_likes;
    private int num_loves;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(facebook.avro.FacebookPost.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status_id)) {
        this.status_id = data().deepCopy(fields()[0].schema(), other.status_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status_message)) {
        this.status_message = data().deepCopy(fields()[1].schema(), other.status_message);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.link_name)) {
        this.link_name = data().deepCopy(fields()[2].schema(), other.link_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status_type)) {
        this.status_type = data().deepCopy(fields()[3].schema(), other.status_type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status_link)) {
        this.status_link = data().deepCopy(fields()[4].schema(), other.status_link);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status_published)) {
        this.status_published = data().deepCopy(fields()[5].schema(), other.status_published);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.num_reactions)) {
        this.num_reactions = data().deepCopy(fields()[6].schema(), other.num_reactions);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.num_comments)) {
        this.num_comments = data().deepCopy(fields()[7].schema(), other.num_comments);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.num_shares)) {
        this.num_shares = data().deepCopy(fields()[8].schema(), other.num_shares);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.num_likes)) {
        this.num_likes = data().deepCopy(fields()[9].schema(), other.num_likes);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.num_loves)) {
        this.num_loves = data().deepCopy(fields()[10].schema(), other.num_loves);
        fieldSetFlags()[10] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FacebookPost instance
     * @param other The existing instance to copy.
     */
    private Builder(facebook.avro.FacebookPost other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.status_id)) {
        this.status_id = data().deepCopy(fields()[0].schema(), other.status_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status_message)) {
        this.status_message = data().deepCopy(fields()[1].schema(), other.status_message);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.link_name)) {
        this.link_name = data().deepCopy(fields()[2].schema(), other.link_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status_type)) {
        this.status_type = data().deepCopy(fields()[3].schema(), other.status_type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status_link)) {
        this.status_link = data().deepCopy(fields()[4].schema(), other.status_link);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status_published)) {
        this.status_published = data().deepCopy(fields()[5].schema(), other.status_published);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.num_reactions)) {
        this.num_reactions = data().deepCopy(fields()[6].schema(), other.num_reactions);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.num_comments)) {
        this.num_comments = data().deepCopy(fields()[7].schema(), other.num_comments);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.num_shares)) {
        this.num_shares = data().deepCopy(fields()[8].schema(), other.num_shares);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.num_likes)) {
        this.num_likes = data().deepCopy(fields()[9].schema(), other.num_likes);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.num_loves)) {
        this.num_loves = data().deepCopy(fields()[10].schema(), other.num_loves);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'status_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusId() {
      return status_id;
    }

    /**
      * Sets the value of the 'status_id' field.
      * @param value The value of 'status_id'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setStatusId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.status_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'status_id' field has been set.
      * @return True if the 'status_id' field has been set, false otherwise.
      */
    public boolean hasStatusId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'status_id' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearStatusId() {
      status_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_message' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusMessage() {
      return status_message;
    }

    /**
      * Sets the value of the 'status_message' field.
      * @param value The value of 'status_message'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setStatusMessage(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.status_message = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status_message' field has been set.
      * @return True if the 'status_message' field has been set, false otherwise.
      */
    public boolean hasStatusMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status_message' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearStatusMessage() {
      status_message = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'link_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getLinkName() {
      return link_name;
    }

    /**
      * Sets the value of the 'link_name' field.
      * @param value The value of 'link_name'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setLinkName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.link_name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'link_name' field has been set.
      * @return True if the 'link_name' field has been set, false otherwise.
      */
    public boolean hasLinkName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'link_name' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearLinkName() {
      link_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusType() {
      return status_type;
    }

    /**
      * Sets the value of the 'status_type' field.
      * @param value The value of 'status_type'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setStatusType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.status_type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status_type' field has been set.
      * @return True if the 'status_type' field has been set, false otherwise.
      */
    public boolean hasStatusType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status_type' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearStatusType() {
      status_type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_link' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusLink() {
      return status_link;
    }

    /**
      * Sets the value of the 'status_link' field.
      * @param value The value of 'status_link'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setStatusLink(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.status_link = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status_link' field has been set.
      * @return True if the 'status_link' field has been set, false otherwise.
      */
    public boolean hasStatusLink() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status_link' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearStatusLink() {
      status_link = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_published' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatusPublished() {
      return status_published;
    }

    /**
      * Sets the value of the 'status_published' field.
      * @param value The value of 'status_published'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setStatusPublished(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.status_published = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status_published' field has been set.
      * @return True if the 'status_published' field has been set, false otherwise.
      */
    public boolean hasStatusPublished() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status_published' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearStatusPublished() {
      status_published = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_reactions' field.
      * @return The value.
      */
    public java.lang.Integer getNumReactions() {
      return num_reactions;
    }

    /**
      * Sets the value of the 'num_reactions' field.
      * @param value The value of 'num_reactions'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setNumReactions(int value) {
      validate(fields()[6], value);
      this.num_reactions = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'num_reactions' field has been set.
      * @return True if the 'num_reactions' field has been set, false otherwise.
      */
    public boolean hasNumReactions() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'num_reactions' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearNumReactions() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_comments' field.
      * @return The value.
      */
    public java.lang.Integer getNumComments() {
      return num_comments;
    }

    /**
      * Sets the value of the 'num_comments' field.
      * @param value The value of 'num_comments'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setNumComments(int value) {
      validate(fields()[7], value);
      this.num_comments = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'num_comments' field has been set.
      * @return True if the 'num_comments' field has been set, false otherwise.
      */
    public boolean hasNumComments() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'num_comments' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearNumComments() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_shares' field.
      * @return The value.
      */
    public java.lang.Integer getNumShares() {
      return num_shares;
    }

    /**
      * Sets the value of the 'num_shares' field.
      * @param value The value of 'num_shares'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setNumShares(int value) {
      validate(fields()[8], value);
      this.num_shares = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'num_shares' field has been set.
      * @return True if the 'num_shares' field has been set, false otherwise.
      */
    public boolean hasNumShares() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'num_shares' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearNumShares() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_likes' field.
      * @return The value.
      */
    public java.lang.Integer getNumLikes() {
      return num_likes;
    }

    /**
      * Sets the value of the 'num_likes' field.
      * @param value The value of 'num_likes'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setNumLikes(int value) {
      validate(fields()[9], value);
      this.num_likes = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'num_likes' field has been set.
      * @return True if the 'num_likes' field has been set, false otherwise.
      */
    public boolean hasNumLikes() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'num_likes' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearNumLikes() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_loves' field.
      * @return The value.
      */
    public java.lang.Integer getNumLoves() {
      return num_loves;
    }

    /**
      * Sets the value of the 'num_loves' field.
      * @param value The value of 'num_loves'.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder setNumLoves(int value) {
      validate(fields()[10], value);
      this.num_loves = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'num_loves' field has been set.
      * @return True if the 'num_loves' field has been set, false otherwise.
      */
    public boolean hasNumLoves() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'num_loves' field.
      * @return This builder.
      */
    public facebook.avro.FacebookPost.Builder clearNumLoves() {
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    public FacebookPost build() {
      try {
        FacebookPost record = new FacebookPost();
        record.status_id = fieldSetFlags()[0] ? this.status_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.status_message = fieldSetFlags()[1] ? this.status_message : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.link_name = fieldSetFlags()[2] ? this.link_name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.status_type = fieldSetFlags()[3] ? this.status_type : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.status_link = fieldSetFlags()[4] ? this.status_link : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.status_published = fieldSetFlags()[5] ? this.status_published : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.num_reactions = fieldSetFlags()[6] ? this.num_reactions : (java.lang.Integer) defaultValue(fields()[6]);
        record.num_comments = fieldSetFlags()[7] ? this.num_comments : (java.lang.Integer) defaultValue(fields()[7]);
        record.num_shares = fieldSetFlags()[8] ? this.num_shares : (java.lang.Integer) defaultValue(fields()[8]);
        record.num_likes = fieldSetFlags()[9] ? this.num_likes : (java.lang.Integer) defaultValue(fields()[9]);
        record.num_loves = fieldSetFlags()[10] ? this.num_loves : (java.lang.Integer) defaultValue(fields()[10]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
